function [road_perim] = adaptive_perimeter_update(previous_road, hsc1)

    [rows, cols] = size(previous_road);
    previous_road(:,1:2)=0;
    previous_road(:,end-1:end)=0;
    imshow(previous_road > 0)
    [xR,yR] = find(hsc1 & previous_road);
    centroid = [mean(xR), mean(yR)];
    dx = floor((centroid(1) - min(xR)) / 2);
    
    A = poly2mask([min(yR),...
                   floor(centroid(2)) - dx,...
                   floor(centroid(2)) + dx,...
                   max(yR)],...
                   [rows-1,...
                   min(xR) + 2 * dx,...
                   min(xR) + 2 * dx,...
                   rows-1],...
                   rows,...
                   cols);
    [min(yR),...
                   floor(centroid(2)) - dx,...
                   floor(centroid(2)) + dx,...
                   max(yR)],...
                   [rows-1,...
                   min(xR) + 2 * dx,...
                   min(xR) + 2 * dx,...
                   rows-1]
    road_perim = hsc1 & bwperim(A);
end